export default {
    loginTitle: 'Авторизация',
    button_forgot: 'Забыли?',
    button_login: 'Войти',
    button_save: 'Сохранить',
    alt_login: 'Или войдите с ...',
    email: 'Email',
    password: 'Пароль',
    newToTheApp: 'Нет аккаунта?',
    register: 'Регистрация',
    alt_register: 'Или используйте email для регистрации',
    alreadyRegister: 'Уже есть аккаунт?',
    fullName: 'Полное имя',
    confirmPassword: 'Повторите пароль',

    login: 'Логин',
    avatar: 'Аватар',
    imageSelect: 'Выбрать из галереи',
    imageTakeCamera: 'Получить с камеры',
    formUserTitle: 'Основная информация',
    formAvatarTitle: 'Аватар пользователя',
};
